FROM postgres:12-alpine

# RUN pg_basebackup -h pg_master -D /var/lib/postgresql/data -R --progress -U admin
# RUN echo 'CREATE ROLE repl_user LOGIN REPLICATION' | psql -h127.0.0.1 -p5432 -Uadmin postgres
